spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mymusicdiary02.chyamimmab8z.ap-northeast-2.rds.amazonaws.com:13306/MyMusicDiary_2
    username: admin
    password: Admin-diary
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        ddl-auto: update
    generate:
      ddl: true

#-----------------------------------------------------------------------

## h2 설정
#spring:
#  h2:
#    console:
#      enabled: true
#      path: /h2
#  datasource:
#    url: jdbc:h2:mem:test
#  jpa:
#    hibernate:
#      ddl-auto: create  # (1) 스키마 자동 생성
#    show-sql: true      # (2) SQL 쿼리 출력
#    properties:
#      hibernate:
#        format_sql: true  # (3) SQL pretty print
#  sql:
#    init:
#      data-locations: classpath*:db/h2/data.sql
#  devtools:
#    livereload:
#      enabled: true     # livereload 사용시 활성화
#    restart:
#      enabled: true


#--------------------------------------------------

logging:
  level:
    org:
      springframework:
        orm:
          jpa: DEBUG
      hibernate.SQL: debug
server:
  servlet:
    encoding:
      force-response: true
#  port:
#    8000
jwt:
  key: "j4nsK69sMIw67xksgHJoLXNwcmluZy1ib290LWp3dC10dXRvcmladsjkhz76HJFGukiy1209VHrKIOy7TDjr7420fgGFWnNO472CHhzbzZWNyZXQK"
  access-token-expiration-minutes: 10000
  refresh-token-expiration-minutes: 420
servlet:
  multipart:
    max-file-size: 10MB
    max-request-size: 10MB

cloud:
  aws:
    credentials:
      accessKey: AKIASX4YIIHRXX274JCF
      secretKey: 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
    s3:
      bucket: main30
    region:
      static: ap-northeast-2
    stack:
      auto: false